name: Build package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  buld_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: dependencies
        run: |
          python -m pip install -U pip build
          pip install -r requirements.txt

      - name: build
        id: build
        run: |
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*

  build_wheels:
    name: Build wheels py${{ matrix.buildplat[2] }}-${{ matrix.buildplat[0] }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      matrix:
        buildplat:
          - [ windows-2022, x64, "3.7" ]
          - [ windows-2022, x86, "3.7" ]
          - [ windows-latest, x64, "3.11" ]

    steps:
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.buildplat[2] }}
          architecture: ${{ matrix.buildplat[1] }}

      - name: Setup MinGW
        if: ${{ matrix.buildplat[0] == 'windows-2022' }}
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          platform: ${{ matrix.buildplat[1] }}
          version: "12.2.0"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build wheels
        run: |
          python -m pip install -U pip build
          python -m build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: py${{ matrix.buildplat[2] }}-${{ matrix.buildplat[0] }}-${{ matrix.buildplat[1] }}
          path: ./dist/*.whl
