name: Build package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  buld_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: dependencies
        run: |
          python -m pip install -U pip build
          pip install -r requirements.txt

      - name: build
        id: build
        run: |
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*